### ISSUE TITLE
Transferring permissions for gitconfig-mode et al

### ISSUE THREAD

**Issue by tarsius** [nicferrier/elmarmalade#101]
You probably lost track of https://github.com/magit/git-modes/issues/126 so I am reopening this here.

@nicferrier could you please authorize me to upload:

    gitconfig-mode

Also please remove the permissions for anybody but me for:

    gitconfig-mode
    gitignore-mode
    magit

Thanks!

**Comment by nicferrier** [comment]
Done. Let me know.

**Comment by tarsius** [comment]
Thanks. I can confirm that this package is now listed on profile/tarsius and that I was able to upload 1.2.0.
