### ISSUE TITLE
marmalade-repo certificate expired

### ISSUE THREAD

**Issue by pgroce** [nicferrier/elmarmalade#106]
Can't find anywhere else to bring this up, so: the certificate for the marmalade-repo.org domain expired yesterday, so now the repo is unavailable.

**Comment by cipherself** [comment]
This is still an issue!

**Comment by nicferrier** [comment]
FIxed now. Sorry it took me so long.

I've made it a 3 year cert now, I can't guarantee it won't take me a long time next time, but at least it won't be for 3 years.

**Comment by cipherself** [comment]
@nicferrier No worries, thanks for fixing it and working on marmalade :)
