### ISSUE TITLE
Please remove the ancient git-commit so that I can upload the version required by magit v2.1.0

### ISSUE THREAD

**Issue by tarsius** [nicferrier/elmarmalade#110]
Or just transfer the permissions for that package to me. What I am trying to upload actually is an improved version of this package (as well as other similar packages which I have integrated).

In 2010 @rafl created `git-commit.el` and uploaded it to marmalade. I kept improving it until 2012 but never uploaded a new version. At the end of 2012 @lunaryorn forked the package and renamed it to `git-commit-mode`. In 2013 I merged this `git-commit-mode.el` and magit's `magit-log-edit.el`, keeping the name `git-commit-mode`. Later I renamed it to `git-commit`.

Now I have released v2.1.0 of `magit` and it depends on this new `git-commit` implementation.

Please, @nicferrier, make it possible for me to upload this version.

As you can see in https://github.com/magit/magit/issues/1645, I have carefully prepared this release. Unfortunately I overlooked this issue, I tried my best, but I am not NASA. The release process isn't complete until you have taken action. Please do it asap. Thanks!

**Comment by tarsius** [comment]
While you are at it could you please also do something about magit/git-modes#126 (later reposted as #101) . I opened that issue three months ago and you have not replied yet. Then please also deal with #111.

**Comment by lunaryorn** [comment]
@tarsius Mmh, am I needed in this issue?

**Comment by tarsius** [comment]
Nope :)

**Comment by lunaryorn** [comment]
@tarsius Ah, ok, I'll unsubscribe then.  Ping me if I can contribute…

**Comment by tarsius** [comment]
For updates, see #111.

**Comment by nicferrier** [comment]
Close this now?

**Comment by tarsius** [comment]
Since I am not yet able to upload a new release - no.

**Comment by tarsius** [comment]
Everything works now

Magit v2.1.0 and all its dependencies can be installed from Marmalade.
