### ISSUE TITLE
instructions not clear

### ISSUE THREAD

**Issue by jayknowstheway** [nicferrier/elmarmalade#124]
Hello, I am trying to set up an emacs starter kit. However, when I go to the Marmalade instructions, I can't see what file I should create, what link I should download. I resorted to going to this site:
http://emacswiki.org/emacs/ELPA

and copied this code:

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))
Which doesn't give me any error messages in emacs. However, M-x package-list-packages is not available. I wonder what's going on that's making something I'd think would be simple so complex! I am on a mac OSX, have the Emac 24.5.

**Comment by vyp** [comment]
@jayknowstheway Try `M-x list-packages`?
