### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by johanclaesson** [nicferrier/elmarmalade#82]
Hi, can i get a account to be able to upload marmalade packages?
I would upload an image viewer package called picpocket.el. 
Regards,
/Johan

**Comment by johanclaesson** [comment]
Hi, please let me know if there is anything i should do to get an account. 
Regards,
/Johan

**Comment by nicferrier** [comment]
Hi, sorry for the slow response. I've been in China and then ill.

I've emailed you an account registration. Let me know if it doesn't show!

**Comment by johanclaesson** [comment]
Hi,
No problem.  Thanks a lot, i received the registration mail.
