### ISSUE TITLE
unbable to upload a .tar package to marmalade

### ISSUE THREAD

**Issue by jasonblewis** [nicferrier/elmarmalade#86]
When I try and upload a .tar package to marmalade via the web browser, the browser seems to hang for ages with a ""waiting for marmalade-repo.org" message and eventually it gives up with a "No data received" message.

I have tried in Chrome and Firefox from Windows 7

I also tried over several days with the same result.

**Comment by nicferrier** [comment]
I think this is an ssl problem. Do you want to try the http version?

**Comment by jasonblewis** [comment]
Sure, but afaict, the site just redirects to https?

**Comment by nicferrier** [comment]
No, there's a secret http version if you want it.

**Comment by jasonblewis** [comment]
oh, sure, I'll give the secret version a go

**Comment by nicferrier** [comment]
mail me then. it's secret.

**Comment by jasonblewis** [comment]
turns out my package was broken. fixed package then was able to upload
