### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by raghavgautam** [nicferrier/elmarmalade#87]
Hi, can I have an account? I want to upload my package:
https://github.com/raghavgautam/tramp-hdfs

**Comment by nicferrier** [comment]
Apologies for the slow response. I need an email to send the account to. Can you please either contact me by email or set an email address on your github account?

Thanks!

**Comment by raghavgautam** [comment]
My email is raghavgautam@gmail.com
Thanks

**Comment by nicferrier** [comment]
Sent. But that's very insecure. Which is why I suggested sending me an email.

Let me know if it doesn't arrive.

**Comment by raghavgautam** [comment]
Received and I have changed my password.

Thanks.
