### ISSUE TITLE
Marmalade account registration

### ISSUE THREAD

**Issue by killdash9** [nicferrier/elmarmalade#90]
Can I get a marmalade account?  I'd like to publish a package.

**Comment by nicferrier** [comment]
Sorry for the long wait. I need an email.

**Comment by killdash9** [comment]
Never mind, I put it up on melpa

Sent from my iPhone

On Jul 3, 2015, at 4:16 PM, Nic Ferrier <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry for the long wait. I need an email.
