### ISSUE TITLE
Request for a new account on marmalade

### ISSUE THREAD

**Issue by myTerminal** [nicferrier/elmarmalade#91]
May I please have a new account?
Bounced back from [https://marmalade-repo.org/register-comingsoon/#](https://marmalade-repo.org/register-comingsoon/#).

*Thanks in advance*

**Comment by nicferrier** [comment]
Done. Email on it's way to you now.

Sorry for crazy wait.

**Comment by myTerminal** [comment]
Thanks Nic,

I had lost all the hope I had :)

On Sat, Jul 4, 2015 at 3:46 AM, Nic Ferrier notifications@github.com
wrote:

> Done. Email on it's way to you now.
> 
> Sorry for crazy wait.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicferrier/elmarmalade/issues/91#issuecomment-118433444
> .

## 
- Mohammed Ismail Ansari
  Sr. Software Developer
  http://ismail.teamfluxion.com
